import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { join } from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// A dev build lands in the vault in this repo, next to a `.hotreload` marker,
// so the Hot Reload plugin picks it up the moment esbuild writes it. The
// release build stays at the root, which is what the CI packages.
const pluginDir = join('dev-vault', '.obsidian', 'plugins', 'mindmap-editor');

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtinModules,
  ],
  format: 'cjs',
  target: 'es2021',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: prod ? 'main.js' : join(pluginDir, 'main.js'),
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
}

// The two files the bundle does not contain but the plugin is loaded with.
// esbuild copies and watches them, rather than fs.watch: a single-file watch
// misses a rewrite often enough to leave the vault a version behind, and Hot
// Reload reloads on a styles.css change as readily as on main.js.
const assets = await esbuild.context({
  entryPoints: ['styles.css', 'manifest.json'],
  outdir: pluginDir,
  loader: { '.css': 'copy', '.json': 'copy' },
  logLevel: 'info',
});

await context.watch();
await assets.watch();
